DOTS_ONE = 'dots_1'
DOTS_TWO = 'dots_2'
DOTS_THREE = 'dots_3'
DOTS_FOUR = 'dots_4'
DOTS_FIVE = 'dots_5'
DOTS_SIX = 'dots_6'
DOTS_SEVEN = 'dots_7'
DOTS_EIGHT = 'dots_8'
DOTS_NINE = 'dots_9'

ALL_DOTS = (DOTS_ONE, DOTS_TWO, DOTS_THREE, DOTS_FOUR, DOTS_FIVE, DOTS_SIX, DOTS_SEVEN, DOTS_EIGHT, DOTS_NINE)

BAMBOO_ONE = 'bamboo_1'
BAMBOO_TWO = 'bamboo_2'
BAMBOO_THREE = 'bamboo_3'
BAMBOO_FOUR = 'bamboo_4'
BAMBOO_FIVE = 'bamboo_5'
BAMBOO_SIX = 'bamboo_6'
BAMBOO_SEVEN = 'bamboo_7'
BAMBOO_EIGHT = 'bamboo_8'
BAMBOO_NINE = 'bamboo_9'

ALL_BAMBOO = (BAMBOO_ONE, BAMBOO_TWO, BAMBOO_THREE, BAMBOO_FOUR, BAMBOO_FIVE, BAMBOO_SIX, BAMBOO_SEVEN,
              BAMBOO_EIGHT, BAMBOO_NINE )

CHARACTERS_ONE = 'characters_1'
CHARACTERS_TWO = 'characters_2'
CHARACTERS_THREE = 'characters_3'
CHARACTERS_FOUR = 'characters_4'
CHARACTERS_FIVE = 'characters_5'
CHARACTERS_SIX = 'characters_6'
CHARACTERS_SEVEN = 'characters_7'
CHARACTERS_EIGHT = 'characters_8'
CHARACTERS_NINE = 'characters_9'

ALL_CHARACTERS = (CHARACTERS_ONE, CHARACTERS_TWO, CHARACTERS_THREE, CHARACTERS_FOUR, CHARACTERS_FIVE,
                  CHARACTERS_SIX, CHARACTERS_SEVEN, CHARACTERS_EIGHT, CHARACTERS_NINE)

ALL_SIMPLES = ALL_DOTS + ALL_BAMBOO + ALL_CHARACTERS

WIND_EAST = 'wind_east'
WIND_NORTH = 'wind_north'
WIND_WEST = 'wind_west'
WIND_SOUTH = 'wind_south'

ALL_WINDS = (WIND_EAST, WIND_NORTH, WIND_WEST, WIND_SOUTH)

DRAGON_RED = 'dragon_red'
DRAGON_GREEN = 'dragon_green'
DRAGON_WHITE = 'dragon_white'

ALL_DRAGONS = (DRAGON_RED, DRAGON_GREEN, DRAGON_WHITE)

ALL_HONORS = ALL_WINDS + ALL_DRAGONS

FLOWERS_PLUM = 'flower_plum_1'
FLOWERS_ORCHID = 'flower_orchid_2'
FLOWERS_CHRYSANTHEMUM = 'flower_chrysanthemum_3'
FLOWERS_BAMBOO = 'flower_bamboo_4'

ALL_FLOWERS = (FLOWERS_PLUM, FLOWERS_ORCHID, FLOWERS_CHRYSANTHEMUM, FLOWERS_BAMBOO)

SEASONS_SPRING = 'season_spring_1'
SEASONS_SUMMER = 'season_summer_2'
SEASONS_AUTUMN = 'season_autumn_3'
SEASONS_WINTER = 'season_winter_4'

ALL_SEASONS = (SEASONS_SPRING, SEASONS_SUMMER, SEASONS_AUTUMN, SEASONS_WINTER)

ALL_BONUS = ALL_FLOWERS + ALL_SEASONS

ALL_STONES = ALL_SIMPLES + ALL_HONORS + ALL_BONUS
